### ISSUE TITLE
Yeti theme don't use local fonts

### ISSUE THREAD

**Issue by vpanfilov** [rstudio/shinythemes#7]
All other themes seems to be using local fonts downloaded from googleapis. But the file `shinythemes/inst/shinythemes/css/yeti.min.css` still contains the line:

```css
@import url("https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700");
```

**Comment by vpanfilov** [comment]
I used a simple workaround for Yeti theme:

1.  Copied `yeti.min.css` and all Open Sans fonts from shinythemes package to local `www` folder:

```r
+-- fonts
|   +-- Open_Sans_300.ttf
|   +-- Open_Sans_300italic.ttf
|   +-- Open_Sans_400.ttf
|   +-- Open_Sans_400italic.ttf
|   +-- Open_Sans_700.ttf
|   \-- Open_Sans_700italic.ttf
\-- yeti.min.css
```

2. Replaced the line in `yeti.min.css`:

```css
@import url("https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700");
```

with 

```css
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 300;
  src: url(./fonts/Open_Sans_300.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: url(./fonts/Open_Sans_400.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 700;
  src: url(./fonts/Open_Sans_700.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: italic;
  font-weight: 300;
  src: url(./fonts/Open_Sans_300italic.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: italic;
  font-weight: 400;
  src: url(./fonts/Open_Sans_400italic.ttf) format('truetype');
}
@font-face {
  font-family: 'Open Sans';
  font-style: italic;
  font-weight: 700;
  src: url(./fonts/Open_Sans_700italic.ttf) format('truetype');
}
```

3. Replaced

```r
theme = shinytheme("yeti"),
```

with

```r
theme = "yeti.min.css"
```
